### ISSUE TITLE
Allow click and drag to place many objects

### ISSUE THREAD

**Issue by amarvin** [simpsus/pyGemTD#1]
https://stackoverflow.com/a/41336876/6068036

**Comment by simpsus** [comment]
In the original gem TD game you always place the tiles one by one.
Currently, the grid is so large that this is bordering torture.

Would you also want to free blocks using drag?
What should happen to a blocked tile that is being draged over? Nothing, flip, depending on the first tile that was clicked on?

**Comment by amarvin** [comment]
I was thinking flip.

That could change with future features though. Like I think you are planning to implement an object selector (either click on a toolbar to select object type to place or keyboard shift/control/etc. to select).

**Comment by simpsus** [comment]
flip seemed too hard for me, it would constantly flip as long as the mouse is in that tile, so 60 times per second. How it is like this: Left click/drag blocks, right click, no drag, unblocks
