### ISSUE TITLE
fitness function for a maze

### ISSUE THREAD

**Issue by simpsus** [simpsus/pyGemTD#6]
to enable a first naive approach to the maze of optimal length, we need a function that returns the fitness (i.e. the length of the path) for a grid. In pseudocode:

```python
fitness(grid):
  result = 0
  for pair of waypoints:
    result += A_star(pair)
  return result
```

**Comment by amarvin** [comment]
Your `make_path()` does this, although it stores path length as an attribute rather than returning it.

**Comment by simpsus** [comment]
Yes, I did one in the genetic file that is robust against an invalid grid. So you can call `cacluclate_fitness()` and it will set the `valid `and `fitness `flags correctly
